version: '3.8'

services:
  postgres_db:
    image: postgres:16-alpine
    container_name: giropro_postgres_db
    environment:
      POSTGRES_DB: giropro_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d giropro_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:


