services:
  # Frontend - Expo Web Build
  - type: web
    name: giropro-frontend
    env: node
    rootDir: src/frontend
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: npx serve web-build -s -n -p ${PORT}
    envVars:
      - key: NODE_VERSION
        value: 20.19.5
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --openssl-legacy-provider
      - key: EXPO_PUBLIC_API_URL
        value: https://giropro-backend.onrender.com
    plan: free

  # Backend - Flask API
  - type: web
    name: giropro-backend
    env: python
    rootDir: src/backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: giropro-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health
    plan: free

# Banco de dados PostgreSQL
databases:
  - name: giropro-db
    databaseName: giropro_db
    plan: free
