services:
  - type: web
    name: giropro-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    rootDir: backend
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase: 
          name: giropro-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
  - type: web
    name: giropro-frontend
    env: static
    buildCommand: npm install && npm run build-vite
    staticPublishPath: dist
    rootDir: frontend
    envVars:
      - key: VITE_API_URL
        fromService: 
          name: giropro-backend
          property: host

databases:
  - name: giropro-db
    databaseName: giropro_db
    plan: free
