services:
  # Frontend - Expo Web Build
  - type: web
    name: giropro-frontend
    env: node
    buildCommand: npm install && npm run build:web
    startCommand: npm run serve:web
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000
      - key: EXPO_PUBLIC_API_URL
        value: https://giropro-backend.onrender.com
    healthCheckPath: /

  # Backend - Flask API
  - type: web
    name: giropro-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: giropro-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health

# Banco de dados PostgreSQL
databases:
  - name: giropro-db
    databaseName: giropro_db
    plan: free
