services:
  - type: web
    name: giropro-backend
    runtime: node
    plan: free
    region: oregon
    buildCommand: "cd backend && npm install && npm run build"
    startCommand: "cd backend && npm run start"
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: HOST
        value: 0.0.0.0
