services:
  - type: web
    name: giropro-frontend
    env: node
    rootDir: frontend
    buildCommand: |
      rm -rf node_modules package-lock.json .expo &&
      npm cache clean --force &&
      HUSKY=0 npm install --force &&
      npm run build:web
    startCommand: npx serve web-build -s -n -p ${PORT}
    envVars:
      - key: HUSKY
        value: 0
      - key: NODE_VERSION
        value: 20.19.5
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --openssl-legacy-provider
      - key: EXPO_PUBLIC_API_URL
        value: https://giropro-backend.onrender.com
    plan: free
