"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.fuelingRoutes = void 0;
var express_1 = require("express");
var auth_1 = require("../middlewares/auth");
var fuelingsController_1 = require("../controllers/fuelingsController");
var router = (0, express_1.Router)();
router.post('/', auth_1.authMiddleware, fuelingsController_1.createFueling);
router.get('/', auth_1.authMiddleware, fuelingsController_1.getFuelings);
router.get('/:id', auth_1.authMiddleware, fuelingsController_1.getFuelingById);
router.put('/:id', auth_1.authMiddleware, fuelingsController_1.updateFueling);
router.delete('/:id', auth_1.authMiddleware, fuelingsController_1.deleteFueling);
exports.fuelingRoutes = router;
