name: CI - Quality & Security (front+back)

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # Sonar gosta do histórico completo

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 18

      # ---------- BACKEND ----------
      - name: Install backend deps
        run: npm ci || npm install
        working-directory: backend

      - name: Build backend
        run: npm run build --if-present
        working-directory: backend

      # ---------- FRONTEND ----------
      - name: Install frontend deps
        run: npm ci || npm install
        working-directory: frontend

      - name: Build frontend
        run: npm run build --if-present
        working-directory: frontend

      # ---------- SONARCLOUD ----------
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # ---------- SNYK (BACKEND) ----------
      - name: Snyk Test (backend)
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --severity-threshold=high --file=backend/package.json

      # ---------- SNYK (FRONTEND) ----------
      - name: Snyk Test (frontend)
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --severity-threshold=high --file=frontend/package.json

      # (Opcional) Enviar “monitor” pro dashboard do Snyk sem quebrar o build
      - name: Snyk Monitor (backend)
        if: always()
        continue-on-error: true
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --file=backend/package.json

      - name: Snyk Monitor (frontend)
        if: always()
        continue-on-error: true
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --file=frontend/package.json
