name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instala dependências do backend
      - name: Install backend deps
        run: npm install
        working-directory: backend

      # Build backend (se tiver script build)
      - name: Build backend
        run: npm run build --if-present
        working-directory: backend

      # Instala dependências do frontend
      - name: Install frontend deps
        run: npm install
        working-directory: frontend

      # Build frontend (se tiver script build)
      - name: Build frontend
        run: npm run build --if-present
        working-directory: frontend

      # Rodar análise Sonar
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
